language: perl
install:
  - "cpanm --notest Module::Build ExtUtils::ParseXS"
  - "cpanm --with-recommends --with-suggests --installdeps --notest ."
perl:
  - "5.14"
  - "5.16"
  - "blead"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto