language: perl
install:
  - "cpanm --notest Module::Build ExtUtils::ParseXS"
  - "cpanm --with-recommends --with-suggests --installdeps --notest ."
perl:
  - "5.14"
  - "5.16"
  - "blead"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
